FROM docker.io/library/alpine
RUN apk add --no-cache openjdk8-jre openjdk17-jre openjdk21-jre curl screen

ENV MINECRAFT_VERSION=1.21.3
ENV FABRIC_LOADER_VERSION=0.16.7
ENV FABRIC_INSTALLER_VERSION=1.0.1

WORKDIR /app
COPY files/* .
RUN curl -o server.jar https://meta.fabricmc.net/v2/versions/loader/${MINECRAFT_VERSION}/${FABRIC_LOADER_VERSION}/${FABRIC_INSTALLER_VERSION}/server/jar

WORKDIR /data
RUN echo "eula=true" > eula.txt

CMD trap /app/stop.sh TERM; screen -DmS minecraft java -jar /app/server.jar nogui & wait $!
